name = "strecha-api"
compatibility_date = "2026-02-12"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "LEADS"
id = "f9a734dcc29e4bb9abcc0806953dac18"
preview_id = "877707eac5cc4cbfb48709aea29c9731"

[vars]
NOTIFY_WEBHOOK_URL = ""
STRIPE_WEBHOOK_SECRET = ""
